### ISSUE TITLE
Hi! I got one question

### ISSUE THREAD

**Issue by OmaKing** [not-a-user/raw2iso#1]
How can I run raw2iso.py? I hope you won't mind explaining to me about how to run it. Thank you very much.

**Comment by not-a-user** [comment]
see https://github.com/not-a-user/raw2iso#usage

**Comment by OmaKing** [comment]
Hi, I am not sure about this command. I have to type this command in command prompt or terminal. right?

**Comment by not-a-user** [comment]
Yes - after [compiling](https://github.com/not-a-user/raw2iso#compiler-command-line-example) the command from the C source file according to the instructions given in the [README](https://github.com/not-a-user/raw2iso/blob/master/README.md). - Or download the Windows version from the [Releases](https://github.com/not-a-user/raw2iso/releases) page.
